# Generated by Django 3.1.2 on 2020-11-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='followed',
            field=models.BooleanField(default=False),
        ),
    ]
