# Generated by Django 3.1.2 on 2020-11-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_post_followed'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='followed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='follower_count',
            field=models.IntegerField(default=0),
        ),
    ]
