# Generated by Django 3.1.2 on 2020-12-09 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_user_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='followed',
        ),
        migrations.RemoveField(
            model_name='post',
            name='followed_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='follower_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likecount',
        ),
        migrations.RemoveField(
            model_name='user',
            name='poster',
        ),
        migrations.AddField(
            model_name='user',
            name='followed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='follower_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='likecount',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='likedBy', to='network.post')),
                ('postLiked', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='likePost', to='network.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Followed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='followedBy', to='network.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followLike', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
