# Generated by Django 3.1.2 on 2020-12-15 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_auto_20201209_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='postLiked',
            field=models.IntegerField(default=0),
        ),
    ]
