# Generated by Django 3.1.2 on 2020-12-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_auto_20201222_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='postLiked',
            field=models.IntegerField(default=0),
        ),
    ]
