# Generated by Django 3.1.2 on 2020-12-26 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_auto_20201226_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='postlike',
        ),
    ]
