# Generated by Django 3.1.2 on 2020-12-26 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_remove_user_postlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='postlike',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='userlike', to='network.post'),
            preserve_default=False,
        ),
    ]
