# Generated by Django 3.1.2 on 2020-12-26 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_user_postlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='postlike',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='userlike', to='network.post'),
        ),
    ]
