# Generated by Django 3.1.2 on 2020-12-26 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0019_auto_20201226_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='postlike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='userlike', to='network.post'),
        ),
    ]
