# Generated by Django 3.1.2 on 2020-12-28 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0020_auto_20201226_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='postlike',
        ),
        migrations.AlterField(
            model_name='like',
            name='postLiked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='userlike', to='network.post'),
        ),
    ]
