# Generated by Django 3.1.2 on 2020-12-28 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0023_auto_20201228_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_like',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='postlike', to='network.like'),
        ),
    ]
