# Generated by Django 3.1.2 on 2021-01-02 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0025_auto_20201228_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followed',
            name='followed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='following', to='network.post'),
        ),
        migrations.AlterField(
            model_name='followed',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followBy', to=settings.AUTH_USER_MODEL),
        ),
    ]
